"""add biz_master table with check constraint

Revision ID: e5dd390c9655
Revises: 
Create Date: 2026-10-09 17:40:09.129499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5dd390c9655'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_master',
    sa.Column('id', sa.Integer(), nullable=False, comment='システム内部ID（サロゲートキー）'),
    sa.Column('business_code', sa.String(length=50), nullable=False, comment='業務コード（システム全体で一意となるビジネスキー）'),
    sa.Column('client_code', sa.String(length=50), nullable=False, comment='顧客コード（該当業務を所有・委託するクライアントの識別子）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='業務名称（例: 〇〇様向け日次照合業務）'),
    sa.Column('schedule_rule', sa.String(length=100), nullable=True, comment='実行スケジュール規則（例: Every_Monday）'),
    sa.Column('manager_email', sa.String(length=100), nullable=True, comment='業務管理者のメールアドレス（異常時のエスカレーション先等を想定）'),
    sa.Column('description', sa.Text(), nullable=True, comment='業務の概要・補足説明'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード最終更新日時'),
    sa.CheckConstraint("business_code LIKE client_code || '%%'", name='check_biz_code_prefix_match'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_master_business_code'), 'biz_master', ['business_code'], unique=True)
    op.create_index(op.f('ix_biz_master_client_code'), 'biz_master', ['client_code'], unique=False)
    op.create_index(op.f('ix_biz_master_id'), 'biz_master', ['id'], unique=False)
    op.drop_index(op.f('ix_calendar_axis_day_id'), table_name='calendar_axis')
    op.drop_table('calendar_axis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_axis',
    sa.Column('day_id', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_workday', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_holiday', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('day_id', name=op.f('calendar_axis_pkey'))
    )
    op.create_index(op.f('ix_calendar_axis_day_id'), 'calendar_axis', ['day_id'], unique=False)
    op.drop_index(op.f('ix_biz_master_id'), table_name='biz_master')
    op.drop_index(op.f('ix_biz_master_client_code'), table_name='biz_master')
    op.drop_index(op.f('ix_biz_master_business_code'), table_name='biz_master')
    op.drop_table('biz_master')
    # ### end Alembic commands ###
